FROM ubuntu
RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends tzdata
RUN apt-get -y install apache2
COPY . /var/www/html
ENV name DevOps Dotsquares
ENTRYPOINT apachectl -D FOREGROUND
